/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zheng_com_GetString */

#ifndef _Included_zheng_com_GetString
#define _Included_zheng_com_GetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zheng_com_GetString
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zheng_com_GetString_getStr
  (JNIEnv *, jclass);

/*
 * Class:     zheng_com_GetString
 * Method:    GetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zheng_com_GetString_GetString
  (JNIEnv *, jobject);

/*
 * Class:     zheng_com_GetString
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_zheng_com_GetString_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
