/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zheng_com_GetInt */

#ifndef _Included_zheng_com_GetInt
#define _Included_zheng_com_GetInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zheng_com_GetInt
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zheng_com_GetInt_getInt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
